name: Build
on:
  push:
    branches: [master, CI]
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-22.04
  steps:
    - name: checkout
    - uses: actions/checkout@v4
    - name: install_deps
    - run: apt-get install git help2man perl python3 make autoconf g++ flex bison ccache \
    apt-get install libgoogle-perftools-dev numactl perl-doc \
    apt-get install libfl2 \
    apt-get install libfl-dev \
    apt-get install zlibc zlib1g zlib1g-dev
    apt-get install shellcheck
    -name: run_all
    -run: ./CI/all.sh
